base_config:
  - ./config_base.yaml
  - ./sr_base.yaml
# model
hidden_size: 64
rrdb_num_block: 8
rrdb_num_feat: 32
rrdb_ckpt: ''
use_rrdb: true
fix_rrdb: true
# train and eval
lr: 0.0002
decay_steps: 100000
accumulate_grad_batches: 1
style_interp: false
save_intermediate: false
show_training_process: false
print_arch: false
