raw_data_dir: /home/fguarnera_shared/data_1T/registered_oasis_t1/pairwise_dataset/
binary_data_dir: /home/fguarnera_shared/data_1T/registered_oasis_t1/pairwise_dataset/
sr_scale: 1
eval_batch_size: 20
test_batch_size: 20
