base_config:
  - ../sr_base.yaml
  - ../oasis.yaml
trainer_cls: tasks.rrdb.RRDBOasisTask
# model
hidden_size: 32
lr: 0.0002
num_block: 8

# train and eval
max_updates: 100000
batch_size: 32
eval_batch_size: 20
valid_steps: 10

task: rrdb